---
Name: rest_api_basicauth
After:
  - 'framework/*'
  - 'cms/*'
  - '#rest_api'
---
Injector:
  Authenticator:
    class: Ntb\APIBasicAuth\BasicAuth
  ApiMemberAuthenticator:
    class: Ntb\APIBasicAuth\Authenticator
  SessionValidator:
    class: Ntb\RestAPI\SessionValidator
  PermissionChecks:
    class: Ntb\RestAPI\SilverstripePermission
BaseRestController:
  CORSOrigin: '*'
  CORSMethods: 'GET, PUT, POST, DELETE, OPTIONS'
  CORSMaxAge: '1000'
  CORSAllowHeaders: 'Content-Type, Authorization, X-Requested-With'
  Owner: Member
SessionValidator:
  email_name: email
  password_name: password
NestedResourceRestController:
  root_resource_id_field: ID
